// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenBooksBack.Infrastructure.Data;

#nullable disable

namespace OpenBooks.Infrastructure.Migrations
{
    [DbContext(typeof(OpenBooksContext))]
    partial class OpenBooksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenBooks.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaRevocado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Expira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Comentarios.Denuncia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioDenunciadoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioDenuncianteId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioDenunciadoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioDenuncianteId", "UsuarioDenunciadoId")
                        .IsUnique();

                    b.ToTable("Denuncias", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Comentarios.Resena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LibroId")
                        .HasColumnType("integer");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.HasIndex("UsuarioId", "LibroId")
                        .IsUnique();

                    b.ToTable("Resenas", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Comentarios.Sugerencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sugerencias", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.Biblioteca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Bibliotecas", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.BibliotecaLibro", b =>
                {
                    b.Property<int>("BibliotecaId")
                        .HasColumnType("integer");

                    b.Property<int>("LibroId")
                        .HasColumnType("integer");

                    b.HasKey("BibliotecaId", "LibroId");

                    b.HasIndex("LibroId");

                    b.ToTable("BibliotecaLibro", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.Estanteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BibliotecaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BibliotecaId");

                    b.ToTable("Estanterias", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.EstanteriaLibro", b =>
                {
                    b.Property<int>("EstanteriaId")
                        .HasColumnType("integer");

                    b.Property<int>("LibroId")
                        .HasColumnType("integer");

                    b.HasKey("EstanteriaId", "LibroId");

                    b.HasIndex("LibroId");

                    b.ToTable("EstanteriaLibro", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Archivo")
                        .HasColumnType("bytea");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Portada")
                        .HasColumnType("bytea");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ValoracionPromedio")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.HasKey("Id");

                    b.ToTable("Libros", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.LibroCategoria", b =>
                {
                    b.Property<int>("LibroId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.HasKey("LibroId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("LibroCategoria", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Usuarios.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Usuarios.Sancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sanciones", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int?>("RolId1")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("RolId1");

                    b.ToTable("Usuarios", "public");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("OpenBooks.Domain.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Comentarios.Denuncia", b =>
                {
                    b.HasOne("OpenBooks.Domain.Entities.Usuarios.Usuario", "UsuarioDenunciado")
                        .WithMany("DenunciasRecibidas")
                        .HasForeignKey("UsuarioDenunciadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenBooks.Domain.Entities.Usuarios.Usuario", "UsuarioDenunciante")
                        .WithMany("DenunciasRealizadas")
                        .HasForeignKey("UsuarioDenuncianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenBooks.Domain.Entities.Usuarios.Usuario", null)
                        .WithMany("Denuncias")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("UsuarioDenunciado");

                    b.Navigation("UsuarioDenunciante");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Comentarios.Resena", b =>
                {
                    b.HasOne("OpenBooks.Domain.Entities.Libros.Libro", "Libro")
                        .WithMany("Resenas")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenBooks.Domain.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany("Resenas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Comentarios.Sugerencia", b =>
                {
                    b.HasOne("OpenBooks.Domain.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany("Sugerencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.Biblioteca", b =>
                {
                    b.HasOne("OpenBooks.Domain.Entities.Usuarios.Usuario", "Usuario")
                        .WithOne("Biblioteca")
                        .HasForeignKey("OpenBooks.Domain.Entities.Libros.Biblioteca", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.BibliotecaLibro", b =>
                {
                    b.HasOne("OpenBooks.Domain.Entities.Libros.Biblioteca", "Biblioteca")
                        .WithMany("BibliotecaLibros")
                        .HasForeignKey("BibliotecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenBooks.Domain.Entities.Libros.Libro", "Libro")
                        .WithMany("BibliotecaLibros")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biblioteca");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.Estanteria", b =>
                {
                    b.HasOne("OpenBooks.Domain.Entities.Libros.Biblioteca", "Biblioteca")
                        .WithMany("Estanterias")
                        .HasForeignKey("BibliotecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biblioteca");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.EstanteriaLibro", b =>
                {
                    b.HasOne("OpenBooks.Domain.Entities.Libros.Estanteria", "Estanteria")
                        .WithMany("EstanteriaLibros")
                        .HasForeignKey("EstanteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenBooks.Domain.Entities.Libros.Libro", "Libro")
                        .WithMany("EstanteriaLibros")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estanteria");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.LibroCategoria", b =>
                {
                    b.HasOne("OpenBooks.Domain.Entities.Libros.Categoria", "Categoria")
                        .WithMany("LibroCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenBooks.Domain.Entities.Libros.Libro", "Libro")
                        .WithMany("LibroCategorias")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Usuarios.Sancion", b =>
                {
                    b.HasOne("OpenBooks.Domain.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany("Sanciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.HasOne("OpenBooks.Domain.Entities.Usuarios.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenBooks.Domain.Entities.Usuarios.Rol", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId1");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.Biblioteca", b =>
                {
                    b.Navigation("BibliotecaLibros");

                    b.Navigation("Estanterias");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.Categoria", b =>
                {
                    b.Navigation("LibroCategorias");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.Estanteria", b =>
                {
                    b.Navigation("EstanteriaLibros");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Libros.Libro", b =>
                {
                    b.Navigation("BibliotecaLibros");

                    b.Navigation("EstanteriaLibros");

                    b.Navigation("LibroCategorias");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Usuarios.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("OpenBooks.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Navigation("Biblioteca")
                        .IsRequired();

                    b.Navigation("Denuncias");

                    b.Navigation("DenunciasRealizadas");

                    b.Navigation("DenunciasRecibidas");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Resenas");

                    b.Navigation("Sanciones");

                    b.Navigation("Sugerencias");
                });
#pragma warning restore 612, 618
        }
    }
}
